---
title: "Project - Part I"
student: Kaimi Huang (kh2908)
objective of research: the objective of the research is to identify factors that relate to high systolic and diastolic blood pressures.
output: html_document
---

```{r}
#title: "Project - Part I"
#student: Kaimi Huang (kh2908)
#objective of research: the objective of the research is to identify factors that relate to high systolic and diastolic blood pressures

library(foreign)
library(magrittr)
library(dplyr)
library(tidyverse)
library(ggplot2)

#use the foreign package to convert SAS xpt files downloaded from CDC's website to csv files
#give each file detailed names to better identify the datasets

data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DEMO.XPT") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DEMO.csv")

Demographic_Variables_and_Sample_Weights <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DEMO.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DSQTOT.XPT") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DSQTOT.csv")

Dietary_Supplement_Use <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_DSQTOT.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BMX.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BMX.csv")

Body_Measures <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BMX.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPXO.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPXO.csv")

Blood_Pressure_Measures <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPXO.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPQ.csv")

Blood_Pressure_Cholesterol_Questionnaire <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_BPQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ALQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ALQ.csv")

Alcohol_Use <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ALQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ECQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ECQ.csv")

Early_Childhood <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_ECQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_HIQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_HIQ.csv")

Health_Insurance <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_HIQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_INQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_INQ.csv")

Income <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_INQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_SLQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_SLQ.csv")

Sleep_Disorders <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_SLQ.csv')


data <- read.xport("/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_OCQ.xpt") 

write.csv(data, file="/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_OCQ.csv")

Occupation <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//P_OCQ.csv')


#import two files containing the detailed names for all datasets' columns 

column_names_1 <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//Variables in the Total Dietary Supplement File.csv')

column_names_2 <- read.csv('/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project//Demo, body measures, blood pressure, etc.csv')

#combine the variable labels and detailed variable names from the two files by first renaming the first two columns in the files. and then merge the data into one data frame called column_names

colnames(column_names_1)[1] <- "variable_labels"
colnames(column_names_1)[2] <- "variable_names"
colnames(column_names_2)[1] <- "variable_labels"
colnames(column_names_2)[2] <- "variable_names"

column_names <- merge(column_names_1, column_names_2, all=TRUE)
class(column_names)
dim(column_names)

#currently, all the datasets contain cryptic column names. in order to better identify data in the datasets, a nested for loop is used to replace the current column labels with detailed column names

#first, create a list to house all the datasets
dataset_list <- list("Demographic_Variables_and_Sample_Weights" = Demographic_Variables_and_Sample_Weights, 
                     "Dietary_Supplement_Use" = Dietary_Supplement_Use, 
                     "Body_Measures" = Body_Measures, 
                     "Blood_Pressure_Measures" = Blood_Pressure_Measures, 
                     "Blood_Pressure_Cholesterol_Questionnaire" = Blood_Pressure_Cholesterol_Questionnaire, 
                     "Alcohol_Use" = Alcohol_Use, 
                     "Early_Childhood" = Early_Childhood, 
                     "Health_Insurance" = Health_Insurance, 
                     "Income" = Income, 
                     "Sleep_Disorders" = Sleep_Disorders, 
                     "Occupation" = Occupation)

#for every dataset in the dataset_list
for (k in seq_along(dataset_list)){
  
  #a placeholder vector called old_colnames takes its existing column labels
  old_colnames <- colnames(dataset_list[[k]])
  
  #every column label in old_colnames
  for (i in seq_along(old_colnames)){
    
    #is compared to all the labels in the column_names data frame
    for (j in seq_along(column_names$variable_labels)){
      
      #if the column label in old_colnames matches any label in column_names's variable_labels, then the column in the dataset will be renamed by the corresponding variable name from column_names's variable_names
      if (old_colnames[i] == column_names$variable_labels[j]){
      colnames(dataset_list[[k]])[i] <- column_names$variable_names[j]
  }
  }
}
}

#the dependent variables are systolic and diastolic blood pressure. since there are three sets of measures in the Blood_Pressure_Measures dataset, it is necessary to check if they are drastically different before deciding which set of observations should be used. 

#before a boxplot is used to compare the blood pressure measure sets, data in the original Blood_Pressure_Measures data frame needs to be manipulated so that all the measures for a particular type is in one column and a categorical variable is created to indicate if a measure is the 1st, 2nd, or 3rd reading.

#one data frame for each set of measures is created 
Blood_Pressure_Measures_1 <- dataset_list[["Blood_Pressure_Measures"]][, c('Respondent sequence number.', 'Systolic - 1st oscillometric reading', 'Diastolic - 1st oscillometric reading')]
Blood_Pressure_Measures_2 <- dataset_list[["Blood_Pressure_Measures"]][, c('Respondent sequence number.', 'Systolic - 2nd oscillometric reading', 'Diastolic - 2nd oscillometric reading')]
Blood_Pressure_Measures_3 <- dataset_list[["Blood_Pressure_Measures"]][, c('Respondent sequence number.', 'Systolic - 3rd oscillometric reading', 'Diastolic - 3rd oscillometric reading')]

#then, a categorical variable is appended to the data frames to identify the number of reading.
Blood_Pressure_Measures_1[,"Reading"] <- rep('1st reading',length(Blood_Pressure_Measures_1$`Respondent sequence number.`))
Blood_Pressure_Measures_2[,"Reading"] <- rep('2nd reading',length(Blood_Pressure_Measures_2$`Respondent sequence number.`))
Blood_Pressure_Measures_3[,"Reading"] <- rep('3rd reading',length(Blood_Pressure_Measures_3$`Respondent sequence number.`))

#columns 2 & 3 are renamed using the same column names so the merge function can combine the three sets of data
colnames(Blood_Pressure_Measures_1)[2:3] <- c('Systolic','Diastolic')
colnames(Blood_Pressure_Measures_2)[2:3] <- c('Systolic','Diastolic')
colnames(Blood_Pressure_Measures_3)[2:3] <- c('Systolic','Diastolic')

#lastly, the merge function is used to combine all the data
Blood_Pressure_Measures <- merge(Blood_Pressure_Measures_1,Blood_Pressure_Measures_2,all = TRUE)
Blood_Pressure_Measures <- merge(Blood_Pressure_Measures_3,Blood_Pressure_Measures,all = TRUE)

#histograms, boxplots, and summary statistics are used to determine the proper set of readings to use
ggplot(Blood_Pressure_Measures_1, aes(Systolic)) +
  geom_histogram(binwidth = 0.10, colour = "blue", bins = 10, na.rm = T) +
  labs(title = "Systolic - First Reading")

ggplot(Blood_Pressure_Measures_2, aes(Systolic)) +
  geom_histogram(binwidth = 0.10, colour = "green", bins = 10, na.rm = T) +
  labs(title = "Systolic - Second Reading")

ggplot(Blood_Pressure_Measures_3, aes(Systolic)) +
  geom_histogram(binwidth = 0.10, colour = "red", bins = 10, na.rm = T) +
  labs(title = "Systolic - Third Reading")

ggplot(Blood_Pressure_Measures_1, aes(Diastolic)) + 
  geom_histogram(binwidth = 0.10, colour = "blue", bins = 10, na.rm = T) +
  labs(title = "Diastolic - First Reading")

ggplot(Blood_Pressure_Measures_2, aes(Diastolic)) + 
  geom_histogram(binwidth = 0.10, colour = "green", bins = 10, na.rm = T) +
  labs(title = "Diastolic - Second Reading")

ggplot(Blood_Pressure_Measures_3, aes(Diastolic)) + 
  geom_histogram(binwidth = 0.10, colour = "red", bins = 10, na.rm = T) +
  labs(title = "Diastolic - Third Reading")

boxplot(Blood_Pressure_Measures$Systolic ~ Blood_Pressure_Measures$Reading)
boxplot(Blood_Pressure_Measures$Diastolic ~ Blood_Pressure_Measures$Reading)

pressure_measure_summaries <- list(
  systolic = list(first = summary(Blood_Pressure_Measures_1$Systolic),
                  second = summary(Blood_Pressure_Measures_2$Systolic),
                  third = summary(Blood_Pressure_Measures_3$Systolic)),
  diastolic = list(first = summary(Blood_Pressure_Measures_1$Diastolic),
                  second = summary(Blood_Pressure_Measures_2$Diastolic),
                  third = summary(Blood_Pressure_Measures_3$Diastolic))
)

print(pressure_measure_summaries)

#based on the graphs and the statistics, the variances among the three readings are negligible. hence, the first readings will be used as the dependent variable
```
```{r}
#the following codes create a scatter plot to verify that systolic and diastolic blood pressures are directly related
ggplot(data = Blood_Pressure_Measures) +  geom_point(mapping = aes(x = Diastolic, y = Systolic, color = Reading), na.rm = TRUE)

#generate summary statistics for each variable
bpm_mean_sd <- Blood_Pressure_Measures %>%
       select(Systolic, Diastolic, Reading) %>%
  
       group_by(Reading) %>%
    
       summarize(sys_mean = mean(Systolic, na.rm=TRUE), 
                 sys_sd = sd(Systolic, na.rm = TRUE), 
                 dia_mean = mean(Diastolic, na.rm = TRUE), 
                 dia_sd = sd(Diastolic, na.rm = TRUE))

print(bpm_mean_sd)
```

```{r}
#according to the American College of Cardiology/American Heart Association Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults published in 2017, each type of blood pressures is categorized into three levels: normal(systolic: less than 120 mm Hg, diastolic: less than 80 mm Hg), elevated/at risk (systolic: 120–129 mm Hg, diastolic: less than 80 mm Hg), and high blood pressure (systolic: 130 mm Hg or higher, diastolic: 80 mm Hg or higher)

#it would be helpful to have sys_blood_pressure_level and dia_blood_pressure_level columns in the Blood_Pressure_Measures_1 data frame for proportion comparisons

#first, create two vectors for blood pressure levels. the vectors will be added to the Blood_Pressure_Measures_1 data frame later
sys_blood_pressure_level <- c()
dia_blood_pressure_level <- c()

#create a placeholder vector called category
category  <- c()

#create a vector for level descriptions
blood_pressure_level_description <- c("normal", "elevated", "high")

#use for and if function to classify blood pressure levels for systolic
for (i in seq_along(Blood_Pressure_Measures_1$Systolic)){
  
  if (is.na(Blood_Pressure_Measures_1$Systolic[i])){
    
    category <- NA
    
  }else if (Blood_Pressure_Measures_1$Systolic[i] >= 130){
  
    category <- blood_pressure_level_description[3]
  
  }else if (Blood_Pressure_Measures_1$Systolic[i] >= 120){
  
   category <- blood_pressure_level_description[2]
  
  }else{
  
    category <- blood_pressure_level_description[1]
  }
  
  sys_blood_pressure_level <- c(sys_blood_pressure_level, category)
}

#use for and if function to classify blood pressure levels for diastolic
for (i in seq_along(Blood_Pressure_Measures_1$Diastolic)){
  
  if (is.na(Blood_Pressure_Measures_1$Diastolic[i])){
    
    category <- NA
    
  }else if (Blood_Pressure_Measures_1$Diastolic[i] >= 80){
  
    category <- blood_pressure_level_description[3]
  
  }else{
  
    category <- blood_pressure_level_description[1]
  }
  
  dia_blood_pressure_level <- c(dia_blood_pressure_level, category)
}

#append the two new vectors to the Blood_Pressure_Measures_1 data frame
Blood_Pressure_Measures_1$sys_blood_pressure_level <- sys_blood_pressure_level
Blood_Pressure_Measures_1$dia_blood_pressure_level <- dia_blood_pressure_level

head(Blood_Pressure_Measures_1)
```

```{r}
#the first variable to explore is gender. in general, do men have a higher or lower blood pressure level than women?

#extract the identifier and gender columns from Demographic_Variables_and_Sample_Weights 
gender <- data.frame('Respondent sequence number.' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Respondent sequence number.`, 'gender' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Gender of the participant.`)

#merge blood pressure measures and gender data frames
gender <- merge(Blood_Pressure_Measures_1, gender, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#filter for male rows and add a gender description column
male <- gender[gender$gender == 1,]
male$gender_description <- rep("male", length(male$gender))

#do the same for female rows
female <- gender[gender$gender == 2,]
female$gender_description <- rep("female", length(female$gender))

#combine the male and female data frames
gender <- merge(male, female, all = TRUE)

write.csv(gender,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/gender.csv")

#use magrittr functions to filter for male and systolic, male and diastolic, female and systolic, and female and diastolic data and then create histograms using the data frames

male_systolic <- male %>%
       select(`Respondent sequence number.`, Systolic, gender_description) 

male_diastolic <- male %>%
       select(`Respondent sequence number.`, Diastolic, gender_description) 

female_systolic <- female %>%
       select(`Respondent sequence number.`, Systolic, gender_description) 

female_diastolic <- female %>%
       select(`Respondent sequence number.`, Diastolic, gender_description) 
       
ggplot(male_systolic, aes(Systolic)) + 
  geom_histogram(binwidth = 5, colour = "white", fill = "navy", na.rm = TRUE) +
  labs(title="Male Systolic Blood Pressue")

ggplot(male_diastolic, aes(Diastolic)) + 
  geom_histogram(binwidth = 5, colour = "white", fill = "navy", na.rm = TRUE) +
  labs(title="Male Diastolic Blood Pressue")
       
ggplot(female_systolic, aes(Systolic)) + 
  geom_histogram(binwidth = 5, colour = "white", fill = "red", na.rm = TRUE) +
  labs(title="Female Systolic Blood Pressue")

ggplot(female_diastolic, aes(Diastolic)) + 
  geom_histogram(binwidth = 5, colour = "white", fill = "red", na.rm = TRUE) +
  labs(title="Female Diastolic Blood Pressue")
 
#boxplots and summary statistics are used to explore the relationship between gender and blood pressure
boxplot(gender$Systolic ~ gender$gender_description)
boxplot(gender$Diastolic ~ gender$gender_description)

#create a vector to house the variable's descriptions. this will be useful for creating summary statistics
description <- c("male", "female")

#create a function to calculate the systolic blood pressure summary statistics of any kind of categorical variable
#the first argument is a data frame. the second parameter argument is an item of a categorical variable. for instance, male of the gender_description categorical variable can be a parameter
systolic_summary_stat <- function(dataframe, parameter){ 
  
  #filter the 8th column of the specified data frame (will have to make sure the categorical description column for the coming data frames is the 8th column) by the parameter. a new data frame is created to house the filtered data
  new_data_frame <- dataframe[dataframe[[8]] == parameter,]
  
  #summary function is used to calculate the systolic statistics for the specified category
  systolic <- summary(new_data_frame[["Systolic"]])

  return (systolic)
}

#create a second function to calculate the diastolic blood pressure summary statistics of any kind of categorical variable
diastolic_summary_stat <- function(dataframe, parameter){
  
  new_data_frame <- dataframe[dataframe[[8]] == parameter,]

  diastolic <- summary(new_data_frame[["Diastolic"]])

  return (diastolic)
}

#create a function to put all the systolic and diastolic summary statistics in one list. this function will be useful later when calculating the summary statistics for different variables

#the function takes two arguments: dataframe, where the data for calculation is from, and length_of_description_vector, which determines the number of summary statistics for each type of blood pressure. for instance, there are two items in the description for the gender variable. so, there will be two summary statistics for systolic blood pressure: one for male and the other for female

create_pressure_measure_summaries <- function(dataframe,length_of_description_vector){
  
  #if the length of the description vector is 2, for instance, there are two groups in gender_description
  if(length_of_description_vector == 2){
    
    #then create a new list, which contains the systolic and diastolic lists. and each list contains the summary statistics for each categorical group
    new_list <- list(  
  
  #for instance, in the systolic list, there are two summary statistics for gender: one for male and the other for female
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]))
)

print(new_list)
    
#next is the situation when the length of the description vector is not 2 but 3. and so on
  } else if (length_of_description_vector == 3){
    
  new_list <- list(  
  
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = systolic_summary_stat(dataframe, description[3])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = diastolic_summary_stat(dataframe, description[3]))
)

print(new_list)
  
  }else if (length_of_description_vector == 4){
    
  new_list <- list(  
  
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = systolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = systolic_summary_stat(dataframe, description[4])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = diastolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = diastolic_summary_stat(dataframe, description[4]))
)

print(new_list)
  
  }else if (length_of_description_vector == 5){
    
  new_list <- list(  
  
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = systolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = systolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = systolic_summary_stat(dataframe, description[5])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = diastolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = diastolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = diastolic_summary_stat(dataframe, description[5]))
)

print(new_list)
  
  }else if (length_of_description_vector == 6){
    
  new_list <- list(  
  
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = systolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = systolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = systolic_summary_stat(dataframe, description[5]),
                  name = description[6], summary_statistic = systolic_summary_stat(dataframe, description[6])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = diastolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = diastolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = diastolic_summary_stat(dataframe, description[5]),
                  name = description[6], summary_statistic = diastolic_summary_stat(dataframe, description[6]))
)

print(new_list)
  
  }else if (length_of_description_vector == 7){
    
  new_list <- list(  
  
  systolic = list(name = description[1], summary_statistic = systolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = systolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = systolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = systolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = systolic_summary_stat(dataframe, description[5]),
                  name = description[6], summary_statistic = systolic_summary_stat(dataframe, description[6]),
                  name = description[7], summary_statistic = systolic_summary_stat(dataframe, description[7])),
  
  diastolic = list(name = description[1], summary_statistic = diastolic_summary_stat(dataframe, description[1]),
                  name = description[2], summary_statistic = diastolic_summary_stat(dataframe, description[2]),
                  name = description[3], summary_statistic = diastolic_summary_stat(dataframe, description[3]),
                  name = description[4], summary_statistic = diastolic_summary_stat(dataframe, description[4]),
                  name = description[5], summary_statistic = diastolic_summary_stat(dataframe, description[5]),
                  name = description[6], summary_statistic = diastolic_summary_stat(dataframe, description[6]),
                  name = description[7], summary_statistic = diastolic_summary_stat(dataframe, description[7]))
)

print(new_list)
  
  }
  
}


pressure_measure_summaries_gender <- create_pressure_measure_summaries(gender, 2)
```


```{r}
#the second variable to explore is age. how is age related to blood pressure?

#extract the identifier and age columns from Demographic_Variables_and_Sample_Weights 
age <- data.frame('Respondent sequence number.' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Respondent sequence number.`, 'age' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Age in years of the participant at the time of screening. Individuals 80 and over are topcoded at 80 years of age.`)

#merge the blood pressure measures and age data frames
age <- merge(Blood_Pressure_Measures_1, age, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#use ggplot scatter plot to explore whether there is a relationship between age and blood pressure
library(ggplot2)
ggplot(age, aes(age, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(age, aes(age, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#create a placeholder character vector called category
category  <- c()

#create a new vector called age_group, which will be added to the age data frame later
age_group <- c()

#use for and if functions to categorize participants' age 
for (i in seq_along(age$age)){
  
  if (age$age[i] >= 65){
  
    category <- "65+"
  
  }else if (age$age[i] >= 45){
  
    category <- "middle age"
  
  }else if (age$age[i] >= 18){
  
    category <- "young adults"
  
  }else if (age$age[i] >= 12){
  
    category <- "teens"
  
  }else if (age$age[i] >= 1){
  
    category <- "children"
  
  }else {

    category <- "infants"  
  }
  age_group <- c(age_group, category)
}

#add the age_group vector to the age data frame
age$age_group <- age_group

#create a vector of age groups in the desired order
description <- c("infants", "children", "teens", "young adults", "middle age", "65+")

#use the factor function to reorder the group levels of age within the data frame so the box plots will appear with an organized order
age$age_group <- factor(age$age_group, levels = description)

#boxplots and summary statistics are used to explore the relationship between age and blood pressure
boxplot(age$Systolic ~ age$age_group)
boxplot(age$Diastolic ~ age$age_group)

#use the function created above to calculate summary statistics
pressure_measure_summaries_age <- create_pressure_measure_summaries(age,length(description))


```

```{r}
#the third variable to explore is race. does a particular race have higher blood pressure than the rest?

#extract the identifier and race columns from Demographic_Variables_and_Sample_Weights 
race <- data.frame('Respondent sequence number.' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Respondent sequence number.`, 'race' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Recode of reported race and Hispanic origin information, with Non-Hispanic Asian Category`)

#merge the blood pressure measures and race data frames
race <- merge(Blood_Pressure_Measures_1, race, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#current race column contains codes. codes will be replaced by detailed descriptions. first, create a vector containing the races in the corresponding code order
description <- c("Mexican American", "Other Hispanic", "White", "Black", "Asian", "Other Race")

#create a new vector for race description, which will be added to the race data frame later
race_description <- c()

#empty the placeholder vector called category
category  <- c()

#use for and if function to match the codes in the race column with descriptions
for (i in seq_along(race$race)){

  if (race$race[i] == 1){
  
    category <- description[1]
  
  }else if (race$race[i] == 2){
  
   category <- description[2]
  
  }else if (race$race[i] == 3){
  
    category <- description[3]
  
  }else if (race$race[i] == 4){
  
    category <- description[4]
  
    #note that there is no 5 in the race codes
  }else if(race$race[i] == 6){
  
    category <- description[5]
  
  }else{
  
    category <- description[6]
  }
  
  race_description <- c(race_description, category)
}

#add the race_description vector to the race data frame
race$race_description <- race_description

write.csv(race,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/race.csv")

#boxplots and summary statistics are used to explore the relationship between age and blood pressure
boxplot(race$Systolic ~ race$race_description)
boxplot(race$Diastolic ~ race$race_description)

#use the function created above to calculate summary statistics
pressure_measure_summaries_race <- create_pressure_measure_summaries(race,length(description))

#based on the boxplots, all races share similar distributions in both kinds of blood pressures. in order to explore the data further, we will create tables and bar charts to explore proportions based on race

#create bar charts to compare proportions
ggplot(race) + geom_bar(mapping = aes(x=race_description, fill = sys_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="race")
ggplot(race) + geom_bar(mapping = aes(x=race_description, fill = dia_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="race")

#create a function to create a table with margin for systolic counts
table_sys <- function (dataframe, categorical_variable){
  
  #the table is by categorical variables and by systolic blood levels and inlcudes NA values
  table_sys <- table(dataframe[,categorical_variable],dataframe[,'sys_blood_pressure_level'],  useNA = 'always') 
  
  #add column and row totals to the table
  table_sys <- addmargins(table_sys)
  
  print(table_sys)
}

#create the same function but for diastolic
table_dia <- function (dataframe, categorical_variable){
  
  #the table is by categorical variables and by diastolic blood levels and inlcudes NA values
  table_dia <- table(dataframe[,categorical_variable],dataframe[,'dia_blood_pressure_level'],  useNA = 'always') 
  
  #add column and row totals to the table
  table_dia <- addmargins(table_dia)
  
  print(table_dia)
}

#use the functions created above to create tables based on race
table_sys_race <-table_sys(race, "race_description")
table_dia_race <-table_dia(race, "race_description")
```


```{r}
#the fourth variable to explore is education. how is the level of education related to blood pressure?

#extract the identifier and education columns from Demographic_Variables_and_Sample_Weights 
education <- data.frame('Respondent sequence number.' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`Respondent sequence number.`, 'education' = dataset_list[["Demographic_Variables_and_Sample_Weights"]]$`What is the highest grade or level of school {you have/SP has} completed or the highest degree {you have/s/he has} received?`)

#merge the blood pressure measures and education data frames
education <- merge(Blood_Pressure_Measures_1, education, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#current education column contains codes. a column containing the detailed descriptions for the codes will be added. first, create a vector containing the education levels in the corresponding code order
description <- c("Less than 9th grade", "9-11th grade", "High school graduate", "Some college", "College graduate or above", "Refused", "Don't Know")

#create a new vector for education level, which will be added to the education data frame later
education_level <- c()

#empty the placeholder vector called category
category  <- c()

#use for and if function to replace the codes in the education column with descriptions
for (i in seq_along(education$education)){

  if (is.na(education$education[i])){
    
    category <- NA
    
  }else if (education$education[i] == 1){
  
    category <- description[1]
  
  }else if (education$education[i] == 2){
  
   category <- description[2]
  
  }else if (education$education[i] == 3){
  
    category <- description[3]
  
  }else if (education$education[i] == 4){
  
    category <- description[4]
  
  }else if(education$education[i] == 5){
  
    category <- description[5]
  
    #note that there is no 6 in the education codes
  }else if(education$education[i] == 7){
  
    category <- description[6]
    
  }else{
    
    category <- description[7]
  }
  
  education_level <- c(education_level, category)
}

#add the education_level vector to the education data frame
education$education_level <- education_level

#use the factor function to reorder the education levels within the data frame so the box plots will appear with an organized order. the order is the same as it appears in the description vector above
education$education_level <- factor(education$education_level, levels = description)

write.csv(education,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/education.csv")

#boxplots and summary statistics are used to explore the relationship between education level and blood pressure
boxplot(education$Systolic ~ education$education_level)
boxplot(education$Diastolic ~ education$education_level)

#use the function created above to calculate summary statistics
pressure_measure_summaries_education <- create_pressure_measure_summaries(education,length(description))

#boxplots suggest no significant difference among the means. in order to explore the data further, we will create tables and bar charts to explore proportions based on education levels

#create bar charts to compare proportions
ggplot(education) + geom_bar(mapping = aes(x=education_level, fill = sys_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="education level")
ggplot(education) + geom_bar(mapping = aes(x=education_level, fill = dia_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="education level")

#use the functions created above to create tables based on education level
table_sys_education <-table_sys(education, "education_level")
table_dia_education <-table_dia(education, "education_level")

```

```{r}
#the fifth variable to explore is daily Vitamin D dietary supplement intake. is a high daily Vitamin D consumption associated with low blood pressure?

#extract the identifier and vitamin d columns from Dietary_Supplement_Use data frame 
vitamin_d <- data.frame('Respondent sequence number.' = dataset_list[["Dietary_Supplement_Use"]]$`Respondent sequence number.`, 'vitamin d' = dataset_list[["Dietary_Supplement_Use"]]$`Vitamin D (D2 + D3) (mcg)`)

#merge the blood pressure measures and vitamin_d data frames
vitamin_d <- merge(Blood_Pressure_Measures_1, vitamin_d, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(vitamin_d, aes(vitamin.d, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(vitamin_d, aes(vitamin.d, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#scatter plots were not very helpful in showing the relationships between the variables

#use the factor function to reorder the blood pressure levels within the data frame so the box plots will appear in the desired order
order <- c("normal", "elevated", "high")
vitamin_d$sys_blood_pressure_level <- factor(vitamin_d$sys_blood_pressure_level, levels = order)
vitamin_d$dia_blood_pressure_level <- factor(vitamin_d$dia_blood_pressure_level, levels = order)


#use magrittr functions to calculate the means and standard deviations of vitamin.d by systolic and diastolic blood pressure levels
vitamin_d_sys_summary_statistics <- vitamin_d %>%
       select('Respondent sequence number.', sys_blood_pressure_level, vitamin.d) %>%
       
       group_by(sys_blood_pressure_level) %>%

       summarize(Mean_vidamin_d = mean(vitamin.d, na.rm=TRUE), SD_vitamin_d = sd(vitamin.d, na.rm = TRUE))

print(vitamin_d_sys_summary_statistics)

vitamin_d_dia_summary_statistics <- vitamin_d %>%
       select('Respondent sequence number.', dia_blood_pressure_level, vitamin.d) %>%
       
       group_by(dia_blood_pressure_level) %>%

       summarize(Mean_vidamin_d = mean(vitamin.d, na.rm=TRUE), SD_vitamin_d = sd(vitamin.d, na.rm = TRUE))

print(vitamin_d_dia_summary_statistics)

#because of the few large values, boxplots look compressed. zoom in to lower vitamin d values
boxplot(vitamin_d$vitamin.d ~ vitamin_d$sys_blood_pressure_level, ylim = c(0,200))
boxplot(vitamin_d$vitamin.d ~ vitamin_d$dia_blood_pressure_level, ylim = c(0,150))
```

```{r}
#the sixth variable to explore is daily dietary fiber intake. is a high daily fiber consumption associated with low blood pressure?

#extract the identifier and dietary fiber columns from Dietary_Supplement_Use data frame 
fiber <- data.frame('Respondent sequence number.' = dataset_list[["Dietary_Supplement_Use"]]$`Respondent sequence number.`, 'fiber' = dataset_list[["Dietary_Supplement_Use"]]$`Dietary fiber (gm)`)

#merge the blood pressure measures and fiber data frames
fiber <- merge(Blood_Pressure_Measures_1, fiber, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(fiber, aes(fiber, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(fiber, aes(fiber, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#scatter plots suggests there is no relationship 

#use the factor function to reorder the blood pressure levels within the data frame so the box plots will appear in the desired order
order <- c("normal", "elevated", "high")
fiber$sys_blood_pressure_level <- factor(fiber$sys_blood_pressure_level, levels = order)
fiber$dia_blood_pressure_level <- factor(fiber$dia_blood_pressure_level, levels = order)

#use magrittr functions to calculate the means and standard deviations of the variable by systolic and diastolic blood pressure levels
fiber_sys_summary_statistics <- fiber %>%
       select('Respondent sequence number.', sys_blood_pressure_level, fiber) %>%
       
       group_by(sys_blood_pressure_level) %>%

       summarize(Mean_fiber = mean(fiber, na.rm=TRUE), SD_fiber = sd(fiber, na.rm = TRUE))

print(fiber_sys_summary_statistics)

fiber_dia_summary_statistics <- fiber %>%
       select('Respondent sequence number.', dia_blood_pressure_level, fiber) %>%
       
       group_by(dia_blood_pressure_level) %>%

       summarize(Mean_fiber = mean(fiber, na.rm=TRUE), SD_fiber = sd(fiber, na.rm = TRUE))

print(fiber_dia_summary_statistics)

#use boxplots to display distributions of vitamin d consumption by blood pressure levels
boxplot(fiber$fiber ~ fiber$sys_blood_pressure_level)
boxplot(fiber$fiber ~ fiber$dia_blood_pressure_level)

```


```{r}
#the seventh variable to explore is Body Mass Index. is a high Body Mass Index associated with high blood pressure?

#extract the identifier and BMI columns from Body_Measures data frame 
bmi <- data.frame('Respondent sequence number.' = dataset_list[["Body_Measures"]]$`Respondent sequence number.`, 'bmi' = dataset_list[["Body_Measures"]]$`Body Mass Index (kg/m**2)`)

#merge the blood pressure measures and bmi data frames
bmi <- merge(Blood_Pressure_Measures_1, bmi, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(bmi, aes(bmi, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(bmi, aes(bmi, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#there seems to be a trend, however, not an obvious one. add the gender_description column from the gender data frame and plot again to see if the trend will be clearer
bmi_gender <- merge(bmi, gender, all = TRUE)

#Color the data points by gender_description
ggplot(data = bmi_gender) +  geom_point(mapping = aes(x = bmi, y = Systolic, color = gender_description))
ggplot(data = bmi_gender) +  geom_point(mapping = aes(x = bmi, y = Diastolic, color = gender_description))

#try the other categorical variables
#age
bmi_age <- merge(bmi, age, all = TRUE)
#Color the data points by age_group
ggplot(data = bmi_age) +  geom_point(mapping = aes(x = bmi, y = Systolic, color = age_group))
ggplot(data = bmi_age) +  geom_point(mapping = aes(x = bmi, y = Diastolic, color = age_group))

#race
bmi_race <- merge(bmi, race, all = TRUE)
#Color the data points by race
ggplot(data = bmi_race) +  geom_point(mapping = aes(x = bmi, y = Systolic, color = race_description))
ggplot(data = bmi_race) +  geom_point(mapping = aes(x = bmi, y = Diastolic, color = race_description))

#education
bmi_education <- merge(bmi, education, all = TRUE)
#Color the data points by education level
ggplot(data = bmi_education) +  geom_point(mapping = aes(x = bmi, y = Systolic, color = education_level))
ggplot(data = bmi_education) +  geom_point(mapping = aes(x = bmi, y = Diastolic, color = education_level))

#the scatter plots do not show the relationships very well. to investigate further, bmi numbers will be separated into 4 categories. and box plots will be used to compare the distribution of the categories

#create a vector containing 4 bmi categories
description <- c("underweight", "normal weight", "overweight", "obesity")

#create a new vector for bmi category, which will be added to the bmi data frame later
bmi_category <- c()

#empty the placeholder vector called category
category  <- c()

#use for and if function to categorize bmi numbers
for (i in seq_along(bmi$bmi)){

  if (is.na(bmi$bmi[i])){
    
    category <- NA
    
  }else if (bmi$bmi[i] >= 30){
  
    category <- description[4]
  
  }else if (bmi$bmi[i] >= 25){
  
   category <- description[3]
  
  }else if (bmi$bmi[i] >= 18.5){
  
    category <- description[2]
  
  }else{
    
    category <- description[1]
  }
  
  bmi_category <- c(bmi_category, category)
}

#add the bmi_category vector to the bmi data frame
bmi$bmi_category <- bmi_category

#use the factor function to reorder the bmi levels within the data frame so the box plots will appear with an organized order. the order is the same as it appears in the description vector above
bmi$bmi_category <- factor(bmi$bmi_category, levels = description)

#boxplots and summary statistics are used to explore the relationship between education level and blood pressure
boxplot(bmi$Systolic ~ bmi$bmi_category)
boxplot(bmi$Diastolic ~ bmi$bmi_category)

#use the function created above to calculate summary statistics
pressure_measure_summaries_bmi <- create_pressure_measure_summaries(bmi,length(description))

```

```{r}
#the eighth variable to explore is alcohol consumption frequency. is a high alcohol consumption frequency associated with high blood pressure?

#extract the identifier and drink frequency columns from Alcohol_Use data frame 
alcohol <- data.frame('Respondent sequence number.' = dataset_list[["Alcohol_Use"]]$`Respondent sequence number.`, 'drink_frequency' = dataset_list[["Alcohol_Use"]]$`Considering all types of alcoholic beverages, during the past 30 days, how many times did you have {5/4} or more drinks on an occasion?`)

#merge the blood pressure measures and alcohol data frames
alcohol <- merge(Blood_Pressure_Measures_1, alcohol, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#the "777" and "999" numbers in the drink_frequency columns represent "refused to answer" and "don't know". since these answers are not helpful to the analysis, they will be omitted. before that, all the rows containing NA values in drink_frequency column will be removed

alcohol <- alcohol[complete.cases(alcohol[,"drink_frequency"]),]
alcohol <- subset(alcohol, drink_frequency != 777)
alcohol <- subset(alcohol, drink_frequency != 999)

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(alcohol, aes(drink_frequency, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(alcohol, aes(drink_frequency, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#explore the interactions between alcohol consumption and categorical variables regarding blood pressure
#gender
alc_gender <- merge(alcohol, gender, all = TRUE)

#Color the data points by gender_description
ggplot(data = alc_gender) +  geom_point(mapping = aes(x = drink_frequency, y = Systolic, color = gender_description))
ggplot(data = alc_gender) +  geom_point(mapping = aes(x = drink_frequency, y = Diastolic, color = gender_description))

#use magrittr functions to calculate the means and standard deviations of the interaction 
alc_gender_summary_statistics <- alc_gender %>%
       select('Respondent sequence number.', drink_frequency, Systolic, Diastolic, gender_description) %>%
       group_by(gender_description) %>%
       summarize(Mean_alc = mean(drink_frequency, na.rm=TRUE), SD_alc = sd(drink_frequency, na.rm = TRUE),
                 Mean_sys = mean(Systolic, na.rm=TRUE), SD_sys = sd(Systolic, na.rm = TRUE),
                 Mean_dia = mean(Diastolic, na.rm=TRUE), SD_dia = sd(Diastolic, na.rm = TRUE))

print(alc_gender_summary_statistics)

#age
alc_age <- merge(alcohol, age, all = TRUE)
#Color the data points by age_group
ggplot(data = alc_age) +  geom_point(mapping = aes(x = drink_frequency, y = Systolic, color = age_group))
ggplot(data = alc_age) +  geom_point(mapping = aes(x = drink_frequency, y = Diastolic, color = age_group))

#use magrittr functions to calculate the means and standard deviations of the interaction 
alc_age_summary_statistics <- alc_age %>%
       select('Respondent sequence number.', drink_frequency, Systolic, Diastolic, age_group) %>%
       group_by(age_group) %>%
       summarize(Mean_alc = mean(drink_frequency, na.rm=TRUE), SD_alc = sd(drink_frequency, na.rm = TRUE),
                 Mean_sys = mean(Systolic, na.rm=TRUE), SD_sys = sd(Systolic, na.rm = TRUE),
                 Mean_dia = mean(Diastolic, na.rm=TRUE), SD_dia = sd(Diastolic, na.rm = TRUE))

print(alc_age_summary_statistics)

#race
alc_race <- merge(alcohol, race, all = TRUE)
#Color the data points by race
ggplot(data = alc_race) +  geom_point(mapping = aes(x = drink_frequency, y = Systolic, color = race_description))
ggplot(data = alc_race) +  geom_point(mapping = aes(x = drink_frequency, y = Diastolic, color = race_description))

#use magrittr functions to calculate the means and standard deviations of the interaction 
alc_race_summary_statistics <- alc_race %>%
       select('Respondent sequence number.', drink_frequency, Systolic, Diastolic, race_description) %>%
       group_by(race_description) %>%
       summarize(Mean_alc = mean(drink_frequency, na.rm=TRUE), SD_alc = sd(drink_frequency, na.rm = TRUE),
                 Mean_sys = mean(Systolic, na.rm=TRUE), SD_sys = sd(Systolic, na.rm = TRUE),
                 Mean_dia = mean(Diastolic, na.rm=TRUE), SD_dia = sd(Diastolic, na.rm = TRUE))

print(alc_race_summary_statistics)

#education
alc_education <- merge(alcohol, education, all = TRUE)
#Color the data points by education level
ggplot(data = alc_education) +  geom_point(mapping = aes(x = drink_frequency, y = Systolic, color = education_level))
ggplot(data = alc_education) +  geom_point(mapping = aes(x = drink_frequency, y = Diastolic, color = education_level))

#use magrittr functions to calculate the means and standard deviations of the interaction 
alc_education_summary_statistics <- alc_education %>%
       select('Respondent sequence number.', drink_frequency, Systolic, Diastolic, education_level) %>%
       group_by(education_level) %>%
       summarize(Mean_alc = mean(drink_frequency, na.rm=TRUE), SD_alc = sd(drink_frequency, na.rm = TRUE),
                 Mean_sys = mean(Systolic, na.rm=TRUE), SD_sys = sd(Systolic, na.rm = TRUE),
                 Mean_dia = mean(Diastolic, na.rm=TRUE), SD_dia = sd(Diastolic, na.rm = TRUE))

print(alc_education_summary_statistics)


```

```{r}
#the ninth variable to explore is whether one is covered by health insurance. do people who have health insurance generally have lower blood pressure?

#extract the identifier and insurance columns from Health_Insurance data frame 
health_insurance <- data.frame('Respondent sequence number.' = dataset_list[["Health_Insurance"]]$`Respondent sequence number.`, 'health insurance' = dataset_list[["Health_Insurance"]]$`{Are you/Is SP} covered by health insurance or some other kind of health care plan? [Include health insurance obtained through employment or purchased directly as well as government programs like Medicare and Medicaid that provide medical care or help pay medical bills.]`)

#merge the blood pressure measures and health_insurance data frames
health_insurance <- merge(Blood_Pressure_Measures_1, health_insurance, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#in the health insurance column, 1 represents "yes", and 2 represents "no." add a column to indicate such information
coverd_by_health_insurance <- vector(mode = "character")

#filtered out all the rows that say yes to being covered by health insurance
yes <- health_insurance[health_insurance$health.insurance == 1, ]

#add the coverd_by_health_insurance column to the yes data frame
yes$coverd_by_health_insurance <- rep("yes", length(yes$health.insurance))

#filtered out all the rows that say no to being covered by health insurance
no <- health_insurance[health_insurance$health.insurance == 2, ]

#add the coverd_by_health_insurance column to the no data frame
no$coverd_by_health_insurance <- rep("no", length(no$health.insurance))

#combine the yes and no data frames
health_insurance <- merge(yes, no, all = TRUE)

write.csv(health_insurance,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/health_insurance.csv")

#boxplots and summary statistics are used to explore the relationship between health insurance and blood pressure
boxplot(health_insurance$Systolic ~ health_insurance$coverd_by_health_insurance)
boxplot(health_insurance$Diastolic ~ health_insurance$coverd_by_health_insurance)

#reuse the systolic_summary_stat and diastolic_summary_stat functions from above
description <- c("yes", "no")

#use the function created above to calculate summary statistics
pressure_measure_summaries_health_insurance <- create_pressure_measure_summaries(health_insurance,length(description))

#based on the boxplots, both groups share similar distributions in both kinds of blood pressures. in order to explore the data further, we will create tables and bar charts to explore proportions based on insurance coverage

#create bar charts to compare proportions
ggplot(health_insurance) + geom_bar(mapping = aes(x=coverd_by_health_insurance, fill = sys_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="covered by insurance?")
ggplot(health_insurance) + geom_bar(mapping = aes(x=coverd_by_health_insurance, fill = dia_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="covered by insruance?")

#use the functions created earlier to create count tables based on insurance coverage and by blood pressure levels
table_sys_insurance <-table_sys(health_insurance, "coverd_by_health_insurance")
table_dia_insurance <-table_dia(health_insurance, "coverd_by_health_insurance")

```

```{r}
#the tenth variable to explore is income. is high income associated with low blood pressure?

#extract the identifier and poverty level index (a ratio of monthly family income to the HHS poverty guidelines specific to family size) columns from Income data frame 
income <- data.frame('Respondent sequence number.' = dataset_list[["Income"]]$`Respondent sequence number.`, 'poverty_level_index' = dataset_list[["Income"]]$`Family monthly poverty level index, a ratio of monthly family income to the HHS poverty guidelines specific to family size.`)

#merge the blood pressure measures and income data frames
income <- merge(Blood_Pressure_Measures_1, income, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

write.csv(income,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/income.csv")

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(income, aes(poverty_level_index, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(income, aes(poverty_level_index, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#use magrittr functions to calculate the means and standard deviations of the variables 
income_summary_statistics <- income %>%
       select('Respondent sequence number.', poverty_level_index) %>%
       
       summarize(Mean_in = mean(poverty_level_index, na.rm=TRUE), 
                 SD_inc = sd(poverty_level_index, na.rm = TRUE),
                 Min_inc = min(poverty_level_index, na.rm = TRUE),
                 Max_inc = max(poverty_level_index, na.rm = TRUE))
                
sys_summary_statistics <- income %>%
       select('Respondent sequence number.', Systolic) %>%
       
       summarize(Mean_sys = mean(Systolic, na.rm=TRUE), 
                 SD_sys = sd(Systolic, na.rm = TRUE),
                 Min_sys = min(Systolic, na.rm = TRUE),
                 Max_sys = max(Systolic, na.rm = TRUE))

dia_summary_statistics <- income %>%
       select('Respondent sequence number.', Diastolic) %>%
       
       summarize(Mean_dia = mean(Diastolic, na.rm=TRUE), 
                 SD_dia = sd(Diastolic, na.rm = TRUE),
                 Min_dia = min(Diastolic, na.rm = TRUE),
                 Max_dia = max(Diastolic, na.rm = TRUE))    

print(income_summary_statistics)
print(sys_summary_statistics)
print(dia_summary_statistics)
```

```{r}
#the eleventh variable to explore is sleep. is poor sleep associated with high blood pressure?

#extract the identifier and sleep columns from Income data frame 
sleep <- data.frame('Respondent sequence number.' = dataset_list[["Sleep_Disorders"]]$`Respondent sequence number.`, 'workday_sleep_hrs' = dataset_list[["Sleep_Disorders"]]$`Number of hours usually sleep on weekdays or workdays.`)

#merge the blood pressure measures and sleep data frames
sleep <- merge(Blood_Pressure_Measures_1, sleep, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

write.csv(sleep,"/Users/kaimihuang/Documents/Study/STATUN2102_001_2022_1 - Applied Statistical Computing/Project/sleep.csv")

#use ggplot to create scatter plots to examine the relationships between the two variables
ggplot(sleep, aes(workday_sleep_hrs, Systolic)) + geom_point(color = "hotpink", na.rm = TRUE)
ggplot(sleep, aes(workday_sleep_hrs, Diastolic)) + geom_point(color = "aquamarine4", na.rm = TRUE)

#use magrittr functions to calculate the means and standard deviations of the variable 
sleep_summary_statistics <- sleep %>%
       select('Respondent sequence number.', workday_sleep_hrs) %>%
       
       summarize(Mean_sleep = mean(workday_sleep_hrs, na.rm=TRUE), 
                 SD_sleep = sd(workday_sleep_hrs, na.rm = TRUE),
                 Min_sleep = min(workday_sleep_hrs, na.rm = TRUE),
                 Max_sleep = max(workday_sleep_hrs, na.rm = TRUE))
```

```{r}
#the last variable to explore is work schedule. how is one's work schedule related to blood pressure?

#extract the identifier and work schedule columns from Occupation data frame 
work_schedule <- data.frame('Respondent sequence number.' = dataset_list[["Occupation"]]$`Respondent sequence number.`, 'work_schedule' = dataset_list[["Occupation"]]$`Which of the following best describes your overall work schedule (include all jobs) for the last three months?`)

#merge the blood pressure measures and work_schedule data frames
work_schedule <- merge(Blood_Pressure_Measures_1, work_schedule, by.x = "Respondent sequence number.", by.y = "Respondent.sequence.number.", all.x = TRUE)

#reuse the description vector to house descriptions for the work_schedule codes
description <- c("nine_to_five", "evening_or_nights", "early_mornings", "variable_or_irregular", "refused", "dont_know")

#create a new vector for work schedule description, which will be added to the work_schedule data frame later
work_schedule_description <- c()

#empty the placeholder vector called category
category  <- c()

#use for and if function to match codes with descriptions
for (i in seq_along(work_schedule$work_schedule)){

  if (is.na(work_schedule$work_schedule[i])){
    
    category <- "na"
    
  }else if (work_schedule$work_schedule[i] == 1){
  
    category <- description[1]
  
  }else if (work_schedule$work_schedule[i] == 2){
  
   category <- description[2]
  
  }else if (work_schedule$work_schedule[i] == 3){
  
    category <- description[3]
  
  }else if (work_schedule$work_schedule[i] == 5){ #there is no code 4
  
    category <- description[4]
  
  }else if (work_schedule$work_schedule[i] == 7){ #there is no code 6
  
    category <- description[5]
  
  }else{
    
    category <- description[6]
  }
  
  work_schedule_description <- c(work_schedule_description, category)
}

#add the work_schedule_description vector to the work_schedule data frame
work_schedule$work_schedule_description <- work_schedule_description

#exclude rows that say "na" in the work_schedule_description column
work_schedule <- work_schedule[work_schedule_description != "na",]

#boxplots and summary statistics are used to explore the relationship between education level and blood pressure
boxplot(work_schedule$Systolic ~ work_schedule$work_schedule_description)
boxplot(work_schedule$Diastolic ~ work_schedule$work_schedule_description)

#use the function created above to calculate summary statistics
pressure_measure_summaries_work_schedule <- create_pressure_measure_summaries(work_schedule,length(description))

#to explore the variable in a different way. create bar charts to compare proportions
ggplot(work_schedule) + geom_bar(mapping = aes(x=work_schedule_description, fill = sys_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="work schedule?")
ggplot(work_schedule) + geom_bar(mapping = aes(x=work_schedule_description, fill = dia_blood_pressure_level), width=0.95, alpha=0.80) + labs(x="work schedule?")

#use the functions created earlier to create count tables based on insurance coverage and by blood pressure levels
table_sys_ws <-table_sys(work_schedule, "work_schedule_description")
table_dia_ws <-table_dia(work_schedule, "work_schedule_description")
```

